Product menu with findAll/findByName methods
kasper084/shop pull request #7
Opened 2020-01-11 21:11 UTC by okaba04

2020-01-11 21:21 UTC, oleskafeska requested changes

2020-01-11 21:21 UTC, oleskafeska commented on src/main/java/shop/dao/ProductDAO.java
> +   Product findProductByName(String name);
could u change it to Optional<Product> ?

2020-01-11 21:21 UTC, oleskafeska commented on src/main/java/shop/dao/impl/ProductDAOImpl.java
> +                .findFirst().orElse(null);
it will be Optional here. Remove orElse()

2020-01-11 21:21 UTC, oleskafeska commented on src/main/java/shop/service/impl/ProductServiceImpl.java
> +        if (product!=null) System.out.println(product);
should return Product from method or throw exception smth like ProductNotFoundException. U will catch this exception in menu. And print or product or some message that product not found

2020-01-11 21:21 UTC, oleskafeska commented on src/main/java/shop/service/ProductService.java
> +    void getProductByName (String productName);
method void but u want to GET smth from service. Please change it to return Product

2020-01-11 21:21 UTC, oleskafeska commented on src/main/java/shop/service/ProductService.java
> +    void getAllProducts();
same as previous but List<Product>

2020-01-11 21:21 UTC, oleskafeska commented on src/main/java/shop/service/impl/ProductServiceImpl.java
> +    public void getAllProducts() {
same with this. return from the method list. And print it in the menu or show a message if the list is empty

2020-01-12 00:08 UTC, okaba04 commented
Comments were fixed, ready for review

2020-01-12 12:30 UTC, oleskafeska approved these changes

2020-01-12 12:30 UTC, oleskafeska commented on src/main/java/shop/dao/ProductDAO.java
> +
redundant line

2020-01-12 13:31 UTC, merged